// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/coach-nav/CardHome.tsx": () => import("../components/mockups/coach-nav/CardHome.tsx"),
  "./components/mockups/coach-nav/Sidebar.tsx": () => import("../components/mockups/coach-nav/Sidebar.tsx"),
  "./components/mockups/coach-nav/TabBar.tsx": () => import("../components/mockups/coach-nav/TabBar.tsx"),
  "./components/mockups/learning-map/LearningMap.tsx": () => import("../components/mockups/learning-map/LearningMap.tsx"),
  "./components/mockups/curriculum/CoachCurriculum.tsx": () => import("../components/mockups/curriculum/CoachCurriculum.tsx"),
  "./components/mockups/curriculum/HQCurriculum.tsx": () => import("../components/mockups/curriculum/HQCurriculum.tsx"),
  "./components/mockups/materials/CoachLibrary.tsx": () => import("../components/mockups/materials/CoachLibrary.tsx"),
  "./components/mockups/materials/HQUpload.tsx": () => import("../components/mockups/materials/HQUpload.tsx"),
  "./components/mockups/schedule-picker/SchedulePicker.tsx": () => import("../components/mockups/schedule-picker/SchedulePicker.tsx")
};
